
# Generated by Django 6.0.3 on 2026-04-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0004_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhaar_card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
