# Generated by Django 6.0.3 on 2026-04-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0005_employee_aadhaar_card_number_employee_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Loss of Pay', 'Loss of Pay')], max_length=20),
        ),
    ]
