# Generated by Django 6.0.3 on 2026-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0006_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='requested_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
