# Generated by Django 6.0.3 on 2026-04-11 10:55

import Attendanceapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0007_leaverequest_requested_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True, default=Attendanceapp.models.default_date),
        ),
    ]
