# Generated by Django 6.0.4 on 2026-04-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0008_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='work_mode',
            field=models.CharField(default='Office', max_length=50),
        ),
    ]
